input_text:
  nabaztag_ip_address:
    name: YOUR_IP
    initial: 192.168.1.84
  nabaztag_color_1:
    name: Nabaztag Color 1
    initial: ffff00
  nabaztag_color_2:
    name: Nabaztag Color 2
    initial: 000000

input_boolean:
  nabaztag_awake:
    initial: on
    
input_number:
  nabaztag_ear_left:
    name: Nabaztag Ear Left
    initial: 0
    min: 0
    max: 16
    step: 1
  nabaztag_ear_right:
    name: Nabaztag Ear Right
    initial: 0
    min: 0
    max: 16
    step: 1
  nabaztag_light_speed:
    name: Nabaztag Light Speed
    initial: 700
    min: 0
    max: 2000
    step: 100

group:
  nabaztag_utils:
    name: Nabaztag Utils
    entities:
      - script.nabaztag_moods

script:
  nabaztag_moods:
    alias: Talk!
    sequence:
      - service: rest_command.nabaztag_moods
  nabaztag_wakeup:
    alias: Wake Up
    sequence:
      - service: rest_command.nabaztag_wakeup
      - service: rest_command.nabaztag_light
  nabaztag_sleep:
    alias: Sleep
    sequence:
      - service: rest_command.nabaztag_sleep
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.nabaztag_awake

switch:
  - platform: template
    switches:
      nabaztag_life:
        friendly_name: "Éveillé"
        value_template: "{{ is_state('input_boolean.nabaztag_awake', 'on') }}"
        turn_on:
          - service: script.turn_on
            entity_id: script.nabaztag_wakeup
        turn_off:
          - service: script.turn_on
            entity_id: script.nabaztag_sleep

rest_command:
  nabaztag_moods:
    url: "http://{{ states('input_text.nabaztag_ip_address') }}/cgi-bin/apps/moods"
  nabaztag_wakeup:
    url: "http://{{ states('input_text.nabaztag_ip_address') }}/cgi-bin/wakeup?silent=1"
  nabaztag_sleep:
    url: "http://{{ states('input_text.nabaztag_ip_address') }}/cgi-bin/sleep"
  nabaztag_ears_random:
    url: "http://{{ states('input_text.nabaztag_ip_address') }}/cgi-bin/ears_random"
  nabaztag_ears:
    url: "http://{{ states('input_text.nabaztag_ip_address') }}/cgi-bin/ears?left={{ states('input_number.nabaztag_ear_left') }}&right={{ states('input_number.nabaztag_ear_right') }}&noreset=1"
  nabaztag_light:
    url: "http://{{ states('input_text.nabaztag_ip_address') }}/cgi-bin/leds?pulse=1&color={{ states('input_text.nabaztag_color_1') }}&speed={{ states('input_number.nabaztag_light_speed') }}&color2={{ states('input_text.nabaztag_color_2') }}"
    
sensor:
  - platform: rest
    resource: http://192.168.1.84/cgi-bin/status
    name: KarotzSleep
    value_template: '{{ value_json.sleep }}'
    
automation:
  - alias: Karotz on
    trigger:
      platform: state
      entity_id: sensor.KarotzSleep
      to: '0'
    action:
      - service: input_boolean.turn_on
        entity_id: input_boolean.nabaztag_awake
        
  - alias: Karotz off
    trigger:
      platform: state
      entity_id: sensor.KarotzSleep
      to: '1'
    action:
      - service: input_boolean.turn_off
        entity_id: input_boolean.nabaztag_awake

  - alias: Update nabaztag color 1
    trigger:
      - platform: state
        entity_id: input_text.nabaztag_color_1
    action:
      - service: rest_command.nabaztag_light

  - alias: Update nabaztag color 2
    trigger:
      - platform: state
        entity_id: input_text.nabaztag_color_2
    action:
      - service: rest_command.nabaztag_light

  - alias: Update nabaztag light speed
    trigger:
      - platform: state
        entity_id: input_number.nabaztag_light_speed
    action:
      - service: rest_command.nabaztag_light

  - alias: Update nabaztag ear left
    trigger:
      - platform: state
        entity_id: input_number.nabaztag_ear_left
    action:
      - service: rest_command.nabaztag_ears

  - alias: Update nabaztag ear right
    trigger:
      - platform: state
        entity_id: input_number.nabaztag_ear_right
    action:
      - service: rest_command.nabaztag_ears
      
  - alias: Température sous -10
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_temperature
      below: -10
    action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.nabaztag_color_1
        value: "1a00ff"
    - service: input_text.set_value
      data_template:
        entity_id: input_text.nabaztag_color_2
        value: "000000"
      
  - alias: Température de -10 à 0
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_temperature
      above: -10
      below: 0
    action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.nabaztag_color_1
        value: "003cff"
    - service: input_text.set_value
      data_template:
        entity_id: input_text.nabaztag_color_2
        value: "000000"
      
  - alias: Température de 0 à 10
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_temperature
      above: 0
      below: 10
    action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.nabaztag_color_1
        value: "00FF00"
    - service: input_text.set_value
      data_template:
        entity_id: input_text.nabaztag_color_2
        value: "000000"
      
  - alias: Température de 10 à 20
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_temperature
      above: 10
      below: 20
    action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.nabaztag_color_1
        value: "62ff00"
    - service: input_text.set_value
      data_template:
        entity_id: input_text.nabaztag_color_2
        value: "000000"
      
  - alias: Température de 20 à 30
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_temperature
      above: 20
      below: 30
    action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.nabaztag_color_1
        value: "ff9100"
    - service: input_text.set_value
      data_template:
        entity_id: input_text.nabaztag_color_2
        value: "000000"
      
  - alias: Température supérieure à 30
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_temperature
      above: 30
    action:
    - service: input_text.set_value
      data_template:
        entity_id: input_text.nabaztag_color_1
        value: "ff0000"
    - service: input_text.set_value
      data_template:
        entity_id: input_text.nabaztag_color_2
        value: "000000"
      
  - alias: Risque de pluie < 40%
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/15'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_rain_chance
      above: 10
      below: 40
    action:
    - service: rest_command.nabaztag_ears_random
      
  - alias: Risque de pluie de 40% à 60%
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_rain_chance
      above: 40
      below: 60
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.nabaztag_ear_left
        value: 15
    - service: input_number.set_value
      data_template:
        entity_id: input_number.nabaztag_ear_right
        value: 1
      
  - alias: Risque de pluie > 60%
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_rain_chance
      above: 60
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.nabaztag_ear_left
        value: 9
    - service: input_number.set_value
      data_template:
        entity_id: input_number.nabaztag_ear_right
        value: 13
      
  - alias: Wind 0
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      below: 1
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.nabaztag_light_speed
        value: 2000
      
  - alias: Wind 1
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 1
      below: 5
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.nabaztag_light_speed
        value: 1834
      
  - alias: Wind 2
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 6
      below: 11
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.nabaztag_light_speed
        value: 1668
      
  - alias: Wind 3
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 12
      below: 19
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.nabaztag_light_speed
        value: 1502
      
  - alias: Wind 4
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 20
      below: 28
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.nabaztag_light_speed
        value: 1336
      
  - alias: Wind 5
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 29
      below: 38
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.nabaztag_light_speed
        value: 1170
      
  - alias: Wind 6
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 39
      below: 49
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.nabaztag_light_speed
        value: 1004
      
  - alias: Wind 7
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 50
      below: 61
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.nabaztag_light_speed
        value: 838
      
  - alias: Wind 8
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 62
      below: 74
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.nabaztag_light_speed
        value: 672
      
  - alias: Wind 9
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 75
      below: 88
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.nabaztag_light_speed
        value: 506
      
  - alias: Wind 10
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 89
      below: 102
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.nabaztag_light_speed
        value: 340
      
  - alias: Wind 11
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 103
      below: 117
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.nabaztag_light_speed
        value: 174
      
  - alias: Wind 12
    description: ''
    trigger:
    - platform: time_pattern
      hours: '*'
      minutes: '/5'
      seconds: '0'
    condition:
    - condition: numeric_state
      entity_id: sensor.weather_wind_speed
      above: 118
    action:
    - service: input_number.set_value
      data_template:
        entity_id: input_number.nabaztag_light_speed
        value: 8
